export const APP_NAME = import.meta.env.VITE_APP_NAME;
export const DAPP_ACCEPTED_STORAGE_KEY = import.meta.env.VITE_DAPP_ACCEPTED_STORAGE_KEY;
export const POLKADOT_WS_PROVIDER = import.meta.env.VITE_POLKADOT_WS_PROVIDER;
export const POLKADOT_TESTNET_WS_PROVIDER = import.meta.env.VITE_POLKADOT_TESTNET_WS_PROVIDER;
export const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';
export const POLKADOT_DECIMALS = 12;
export const POLKADOT_TRANSFERABLE = Math.pow(10, POLKADOT_DECIMALS);
